spring:
    application:
        name: GasStationVulnerability
    datasource:
        url: jdbc:postgresql://localhost:5432/gas_station_dss
        username: bieliaiev
        password: pgkyrylo2921
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
